import { useForm } from '@inertiajs/react';

function Input({ label, name, form, type = 'text', required = true, children }) {
    return <label className="tt-field"><span>{label}{required && ' *'}</span>{children || <input type={type} name={name} value={form.data[name]} required={required} onChange={(event) => form.setData(name, event.target.value)} />}{form.errors[name] && <small role="alert">{form.errors[name]}</small>}</label>;
}

function Feedback({ success, form }) {
    return <>{success && <p className="tt-form-success" role="status">{success}</p>}{form.hasErrors && <p className="tt-form-error" role="alert">Please review the highlighted fields and try again.</p>}</>;
}

export function RegistrationForm({ success }) {
    const form = useForm({ parent_name: '', email: '', phone: '', child_name: '', child_age: '', programme: '', message: '', website: '' });
    const submit = (event) => { event.preventDefault(); form.post('/registration-enquiry', { preserveScroll: true, onSuccess: () => form.reset() }); };
    return <form onSubmit={submit} className="tt-form"><Feedback success={success} form={form}/><div className="tt-form-grid"><Input label="Parent / guardian name" name="parent_name" form={form}/><Input label="Email address" name="email" type="email" form={form}/><Input label="Phone number" name="phone" type="tel" form={form}/><Input label="Child's name" name="child_name" form={form}/><Input label="Child's age" name="child_age" form={form}><select required value={form.data.child_age} onChange={e => form.setData('child_age', e.target.value)}><option value="">Select age</option>{['10–23 months','2 years','3 years','4 years'].map(age => <option key={age}>{age}</option>)}</select></Input><Input label="Interested programme" name="programme" form={form}><select required value={form.data.programme} onChange={e => form.setData('programme', e.target.value)}><option value="">Select programme</option>{['Tots Club Basic','Tots Club Plus','Tots Club Premium','Tots Playdate','Tots Dailyplay','Tots Club Afternoon','Not sure yet'].map(item => <option key={item}>{item}</option>)}</select></Input></div><Input label="Anything else we should know?" name="message" form={form} required={false}><textarea rows="5" maxLength="3000" value={form.data.message} onChange={e => form.setData('message', e.target.value)}/></Input><input className="tt-honeypot" tabIndex={-1} autoComplete="off" name="website" aria-hidden="true" value={form.data.website} onChange={e => form.setData('website', e.target.value)}/><button type="submit" className="tt-action" disabled={form.processing}>{form.processing ? 'Sending…' : 'Send registration enquiry →'}</button><p className="tt-form-foot">Our team will use these details only to respond to your enquiry.</p></form>;
}

export function CareerForm({ success }) {
    const form = useForm({ name: '', email: '', phone: '', position: '', experience: '', message: '', website: '' });
    const submit = (event) => { event.preventDefault(); form.post('/career-enquiry', { preserveScroll: true, onSuccess: () => form.reset() }); };
    return <form onSubmit={submit} className="tt-form"><Feedback success={success} form={form}/><div className="tt-form-grid"><Input label="Full name" name="name" form={form}/><Input label="Email address" name="email" type="email" form={form}/><Input label="Phone number" name="phone" type="tel" form={form}/><Input label="Role of interest" name="position" form={form}><select required value={form.data.position} onChange={e => form.setData('position', e.target.value)}><option value="">Select a role</option><option>Teacher / educator</option><option>Childcare assistant</option><option>Administration</option><option>Other</option></select></Input></div><Input label="Relevant experience" name="experience" form={form} required={false}><textarea rows="3" maxLength="3000" value={form.data.experience} onChange={e => form.setData('experience', e.target.value)}/></Input><Input label="Tell us about yourself" name="message" form={form}><textarea rows="5" required maxLength="3000" value={form.data.message} onChange={e => form.setData('message', e.target.value)}/></Input><input className="tt-honeypot" tabIndex={-1} autoComplete="off" name="website" aria-hidden="true" value={form.data.website} onChange={e => form.setData('website', e.target.value)}/><button type="submit" className="tt-action" disabled={form.processing}>{form.processing ? 'Sending…' : 'Send career enquiry →'}</button><p className="tt-form-foot">This is an enquiry, not a confirmed job vacancy. Our team will contact you if there is an opportunity.</p></form>;
}
