import { Head } from '@inertiajs/react';
import { Heart, Lightbulb, ShieldCheck } from 'lucide-react';
import PublicLayout, { Action, PageIntro, Reveal } from './components/PublicLayout';

export default function About() { return <PublicLayout current="/about"><Head title="About Us | Tinta Tots Clubhouse" /><PageIntro eyebrow="Our story" title="A place where childhood" accent="shines." description="Tinta Tots Clubhouse is a nurturing and creative space designed for young children to learn, play and grow." />
    <section className="tt-section"><div className="tt-wrap tt-split"><Reveal><div className="tt-visual"><span className="tt-sticker">Happy children ✦</span><img src="/images/logo.jpg" alt="Tinta Tots Clubhouse logo"/><span className="tt-sticker tt-sticker-bottom">Meaningful learning</span></div></Reveal><Reveal><span className="tt-eyebrow">Who we are</span><h2>Childhood is a time of <em>discovery.</em></h2><p className="tt-lead">Our clubhouse brings together play-based learning and structured activities in a safe, engaging and joyful environment. We support social, emotional, cognitive and physical development while giving every child room to explore their unique potential.</p></Reveal></div></section>
    <section className="tt-section" style={{background:'#e9f1e3'}}><div className="tt-wrap"><Reveal className="tt-section-title"><span className="tt-eyebrow">What guides us</span><h2>Small moments. <em>Strong foundations.</em></h2></Reveal><div className="tt-grid">{[[Heart,'Happy children','Children feel cared for and encouraged to grow.'],[Lightbulb,'Meaningful learning','Curiosity, imagination and discovery are part of each day.'],[ShieldCheck,'A caring environment','A comfortable, welcoming setting for children and families.']].map(([Icon,title,desc],i)=><Reveal key={title} delay={i*100}><article className="tt-card"><span className="tt-icon"><Icon/></span><h3>{title}</h3><p>{desc}</p></article></Reveal>)}</div></div></section>
    <section className="tt-section"><div className="tt-wrap tt-split"><Reveal><span className="tt-eyebrow">Our founder</span><h2>Experience behind <em>every little step.</em></h2><p className="tt-lead">With 15 years in the early childhood education industry, our founder has built playschools, preschools and children's enrichment centres, developed learning modules, and trained educators across Malaysia.</p><div style={{marginTop:28}}><Action href="/contact">Visit Tinta Tots</Action></div></Reveal><Reveal><div className="tt-visual" style={{background:'#f8e2bf'}}><span className="tt-sticker">15 years of experience</span><img src="/images/logo.jpg" alt="Tinta Tots Clubhouse"/></div></Reveal></div></section>
    </PublicLayout>; }
