import { Head } from '@inertiajs/react';
import { Heart, Lightbulb, Users } from 'lucide-react';
import PublicLayout, { PageIntro, Reveal } from './components/PublicLayout';
import { CareerForm } from './components/EnquiryForms';

export default function Careers({ success }) { return <PublicLayout current="/careers"><Head title="Careers | Tinta Tots Clubhouse" /><PageIntro eyebrow="Join our community" title="Make a difference in" accent="little lives." description="Are you passionate about supporting young children? We'd love to hear from people who care about early childhood education." />
    <section className="tt-section"><div className="tt-wrap"><Reveal className="tt-section-title"><span className="tt-eyebrow">Why Tinta Tots</span><h2>Grow where children <em>grow.</em></h2><p>Our brochure describes a caring, play-based environment built around children's curiosity and creativity.</p></Reveal><div className="tt-grid">{[[Heart,'Care with purpose','Support children as they learn, explore and build confidence.'],[Lightbulb,'Keep learning','Bring curiosity and creative ideas to each day.'],[Users,'Grow together','Work with families and fellow educators to support little learners.']].map(([Icon,title,description],i)=><Reveal delay={i*90} key={title}><article className="tt-card"><span className="tt-icon"><Icon/></span><h3>{title}</h3><p>{description}</p></article></Reveal>)}</div></div></section>
    <section className="tt-section" style={{background:'#e9f1e3'}}><div className="tt-wrap tt-enquiry-layout"><Reveal><span className="tt-eyebrow">Career enquiries</span><h2>Let's start a <em>conversation.</em></h2><p className="tt-lead">Tell us who you are, the role you are interested in and why you would like to join. Your message will be delivered to the centre's email inbox.</p><div className="tt-visual" style={{marginTop:35,minHeight:300}}><span className="tt-sticker">Grow with us ✳</span><img src="/images/logo.jpg" alt="Tinta Tots Clubhouse"/></div></Reveal><Reveal delay={100}><CareerForm success={success}/></Reveal></div></section>
    </PublicLayout>; }
