import { Head } from '@inertiajs/react';
import { Clock3, MapPin, Phone } from 'lucide-react';
import PublicLayout, { PageIntro, Reveal } from './components/PublicLayout';

export default function Contact() { return <PublicLayout current="/contact"><Head title="Contact Us | Tinta Tots Clubhouse" /><PageIntro eyebrow="Get in touch" title="Come say" accent="hello." description="Questions about programmes, enrolment or visiting the centre? Reach out to the Tinta Tots team." />
    <section className="tt-section"><div className="tt-wrap"><div className="tt-grid">{[[MapPin,'Visit us','Tinta Residensi, Jalan Nada Bidara 4, Taman Nada Bidara, Labu, Negeri Sembilan'],[Phone,'Call or WhatsApp','017-464 3036'],[Clock3,'Opening hours','Monday–Friday · 7:00 AM–6:00 PM']].map(([Icon,title,detail],i)=><Reveal delay={i*100} key={title}><article className="tt-card" style={{height:'100%'}}><span className="tt-icon"><Icon/></span><h3>{title}</h3><p>{detail}</p></article></Reveal>)}</div><Reveal><div className="tt-note" style={{marginTop:28,display:'flex',gap:15,flexWrap:'wrap',alignItems:'center',justifyContent:'space-between'}}><strong>Ready to talk?</strong><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><a href="https://wa.me/60174643036" className="tt-action" target="_blank" rel="noopener noreferrer">WhatsApp the centre →</a><a href="tel:+60174643036" className="tt-action tt-action-outline">Call us →</a></div></div></Reveal></div></section>
    <section className="tt-section" style={{background:'#e9f1e3'}}><div className="tt-wrap tt-split"><Reveal><span className="tt-eyebrow">Find us</span><h2>Visit our little corner of <em>Labu.</em></h2><p className="tt-lead">Tinta Residensi, Jalan Nada Bidara 4, Taman Nada Bidara, Labu, Negeri Sembilan.</p><div style={{display:'flex',flexWrap:'wrap',gap:16,marginTop:27}}><a href="https://www.google.com/maps/search/?api=1&query=Tinta+Residensi+Jalan+Nada+Bidara+4+Labu+Negeri+Sembilan" target="_blank" rel="noopener noreferrer" className="tt-action">Open directions →</a><a href="https://www.instagram.com/tintatotsclubhouse/" target="_blank" rel="noopener noreferrer" className="tt-action tt-action-outline">Instagram</a></div></Reveal><Reveal><div className="tt-visual"><span className="tt-sticker">We can't wait to meet you!</span><img src="/images/logo.jpg" alt="Tinta Tots Clubhouse" /></div></Reveal></div></section>
    <section className="tt-section"><div className="tt-wrap" style={{textAlign:'center'}}><Reveal><span className="tt-eyebrow">More information</span><h2>Discover the <em>full brochure.</em></h2><p className="tt-lead">Explore the centre's own flipbook for more details about programmes and facilities.</p><a className="tt-action" href="https://heyzine.com/flip-book/80d140f3aa.html" target="_blank" rel="noopener noreferrer">View brochure →</a></Reveal></div></section>
    </PublicLayout>; }
