import { Head } from '@inertiajs/react';
import { BookOpen, Heart, Users, Sparkles, Clock3 } from 'lucide-react';
import PublicLayout, { Action, PageIntro, Reveal } from './components/PublicLayout';

const activities = [[Sparkles,'Sensory & discovery','Hands-on exploration and sensory play.'],[Heart,'Art & craft','Room for expression and creativity.'],[Users,'Music & movement','Sound, rhythm, movement and language.'],[Clock3,'Outdoor learning','Nature activities and active play.'],[BookOpen,'Early foundations','Early maths, language, literacy and problem solving.'],[Heart,'Life skills','Independence, good attitudes and social development.']];
const routine = [['07:00','Arrival & settling in'],['09:00','Breakfast & personal care'],['10:00','Sensory discovery & creative play'],['12:00','Lunch, bath & quiet time'],['13:00','Nap & rest'],['16:00','Snack, exploration & outdoor play'],['17:30','Calm play & parent pick-up']];
export default function Programmes() { return <PublicLayout current="/programmes"><Head title="Programmes | Tinta Tots Clubhouse" /><PageIntro eyebrow="Our programmes" title="Big learning starts with" accent="little adventures." description="Tots Club is our flagship programme, bringing together care, guided activities, meals and plenty of time for play." />
    <section className="tt-section"><div className="tt-wrap tt-split"><Reveal><span className="tt-eyebrow">Tots Club</span><h2>Play is how children <em>find their way.</em></h2><p className="tt-lead">Designed for young children, Tots Club combines play-based learning, creativity, exploration and social interaction. The brochure describes a warm, nature-inspired space and a daily programme that supports overall growth.</p><div style={{marginTop:28}}><Action href="/packages">Explore Tots Club packages</Action></div></Reveal><Reveal><div className="tt-visual"><span className="tt-sticker">Our flagship ✳</span><img src="/images/logo.jpg" alt="Tinta Tots Clubhouse"/><span className="tt-sticker tt-sticker-bottom">Play • Connect • Grow</span></div></Reveal></div></section>
    <section className="tt-section" style={{background:'#e9f1e3'}}><div className="tt-wrap"><Reveal className="tt-section-title"><span className="tt-eyebrow">Discover and create</span><h2>Something new <em>every day.</em></h2></Reveal><div className="tt-grid">{activities.map(([Icon,title,description],i)=><Reveal key={title} delay={(i%3)*90}><article className="tt-card"><span className="tt-icon"><Icon size={27}/></span><h3>{title}</h3><p>{description}</p></article></Reveal>)}</div></div></section>
    <section className="tt-section"><div className="tt-wrap tt-split"><Reveal><span className="tt-eyebrow">A day at Tots Club</span><h2>A gentle rhythm from <em>hello to home.</em></h2><p className="tt-lead">This sample day is based on the centre brochure. A child's activities and timing may vary according to their package and the day's routine.</p></Reveal><Reveal><div className="tt-card">{routine.map(([time,label])=><div key={time} style={{display:'flex',gap:20,padding:'13px 0',borderBottom:'1px solid #e8ede4'}}><strong style={{color:'#c27a54',minWidth:48}}>{time}</strong><span>{label}</span></div>)}</div></Reveal></div></section>
    <section className="tt-section tt-dark"><div className="tt-wrap"><Reveal className="tt-section-title"><span className="tt-eyebrow">Also at Tinta Tots</span><h2>More ways to <em>play and grow.</em></h2><p>Ask the centre about the optional Tots Playdate, Tots Dailyplay and Tots Club Afternoon programmes for ages 2–4.</p><Action href="/packages">Compare the options</Action></Reveal></div></section>
    </PublicLayout>; }
